---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-console-secret
  namespace: openshift-console
  annotations:
    kubernetes.io/service-account.name: openshift-console
type: kubernetes.io/service-account-token
...
