# parent-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rprakashg-redhat/microshift-gitops
    targetRevision: HEAD
    path: deploy/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
